name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - name: 最初にCPUをチェック
        run: sysctl machdep.cpu.brand_string & sysctl -n hw.logicalcpu_max & wget https://media.codeweavers.com/pub/crossover/source/crossover-sources-24.0.1.tar.gz
      - name: b
        run: tar -zcvf crossover-sources-24.0.1.tar.gz crossover
      - name: c
        run: ./configure && make
      - name: d
        run: git clone https://github.com/KhronosGroup/SPIRV-Headers.git && cd SPIRV-Headers && mkdir build && cd build && cmake .. && make install && cd ../..
